### ISSUE TITLE
First off, thanks for doing this.. Not working for me though..

### ISSUE THREAD

**Issue by rolltidehero** [shellaaaron/KingdomLikes-Bot#1]
Traceback (most recent call last):
  File "KingdomLikes.py", line 26, in <module>
    browser = webdriver.Chrome(options=chrome_options)
  File "C:\Users\brownhe\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\brownhe\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\brownhe\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\brownhe\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\brownhe\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot process extension #2
from unknown error: CRX verification failed to parse extension header. Chrome supports only CRX3 format. Does the extension need to be updated?

**Comment by axen1** [comment]
update pls

**Comment by techroy23** [comment]
update pls

**Comment by shellaaaron** [comment]
If you know python, you can update it, I do not have time to work on it.

If you wanted to be added to this project let me know.
